export default function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-200 py-8 mt-10 text-center">
      <p className="text-sm text-gray-400">&copy; {new Date().getFullYear()} Gradiorum. All rights reserved.</p>
      <div className="flex justify-center space-x-4 mt-4">
        <a
          href="https://twitter.com/Gradiorum"
          className="hover:text-xboxGreen transition"
          aria-label="Twitter"
          target="_blank"
          rel="noreferrer"
        >
          Twitter
        </a>
        <a
          href="https://linkedin.com/company/Gradiorum"
          className="hover:text-xboxGreen transition"
          aria-label="LinkedIn"
          target="_blank"
          rel="noreferrer"
        >
          LinkedIn
        </a>
        <a
          href="https://youtube.com/channel/Gradiorum"
          className="hover:text-xboxGreen transition"
          aria-label="YouTube"
          target="_blank"
          rel="noreferrer"
        >
          YouTube
        </a>
      </div>
      <div className="mt-6">
        <p className="mb-2">Join our Mailing List for Updates</p>
        <form id="newsletter-form" className="flex justify-center items-center space-x-2">
          <input
            type="email"
            name="email"
            className="px-3 py-2 rounded border border-gray-600 focus:outline-none"
            placeholder="Your email"
            required
          />
          <button
            type="submit"
            className="px-4 py-2 bg-xboxGreen text-black rounded hover:bg-opacity-80 transition"
          >
            Subscribe
          </button>
        </form>
      </div>
      <div className="mt-6 text-sm text-gray-500 max-w-2xl mx-auto">
        <p>
          <strong>Disclaimer:</strong> All graphical assets on this website are generated by AI. We do not claim
          artistic authorship over these assets. If you are a graphic artist and wish to collaborate or provide
          custom artwork, please reach out to us at{" "}
          <a href="mailto:gradiorum@gmail.com" className="text-xboxGreen underline">
            gradiorum@gmail.com
          </a>.
        </p>
      </div>
    </footer>
  );
}
