name: Deploy Next.js to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # or 20 if you prefer

      - name: Install Dependencies
        run: npm install

      # Optionally restore a build cache to speed up subsequent builds
      - name: Restore .next Cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}

      - name: Build Project for Cloudflare Pages
        run: npm run pages:build
        # This calls "npx @cloudflare/next-on-pages" behind the scenes, 
        # producing .vercel/output/ with static + functions

      - name: Upload build output as artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: .vercel/output

      - name: Deploy to Cloudflare Pages
        # We'll use Wrangler to deploy the .vercel/output directory to 
        # the Cloudflare Pages project
        run: |
          # Just for debugging or clarity:
          echo "Deploying to Cloudflare Pages..."
          npm install --global wrangler
          wrangler pages deploy .vercel/output --project-name <YOUR_CF_PAGES_PROJECT_NAME> --branch main
        env:
          CF_PAGES_BRANCH: main
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

